# .github/workflows/deploy.yml
name: Deploy Frontend
on:
  push:
    branches: [ develop, staging ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'
      
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      
      - name: Build and push container
        uses: azure/docker-login@v1
        with:
          login-server: yourappregistry.azurecr.io
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}
      
      - name: Build & Push Image
        run: |
          BRANCH=${GITHUB_REF##*/}
          docker build -t yourappregistry.azurecr.io/frontend:$BRANCH .
          docker push yourappregistry.azurecr.io/frontend:$BRANCH